---
title: "Authentication document"
output: html_document
runtime: shiny_prerendered
---

```{r setup, include = FALSE}
library(checkr)
```

******************

```{r echo = FALSE}
span("Please log in:")
textInput("user_name", "User ID:")
passwordInput("password", "Password:")
textOutput("login_success")
```

******************


```{r echo = FALSE, context = "server"}
# Very, very simple for now.
output$login_success <- renderText({"Please log in."})
output$login_success <-
  renderText({
    Accounts <- checkr:::get_accounts()
    id <- input$user_name
    password <- input$password
    if (is.null(Accounts)) return("No accounts set up yet.")
    else {
      ind <- which(id == Accounts$id)
      if (length(ind) > 0) {
        if (password == Accounts$passwd[ind[1]] ) {
          checkr::set_user_name(id)
          return("Login successful.")
        } else {
          checkr::set_user_name("") # accept entries, but no user id
          return("Wrong password!")
        }
      } else {
        checkr::set_user_name("") # accept entries, but no user id
        return("Invalid user id.")
      }
    }
  })

```
